[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 100
[theme]
primaryColor = "#F39C12"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#000000"
font = "sans serif"